// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/admin-cosmos/Dashboard.tsx": () => import("../components/mockups/admin-cosmos/Dashboard.tsx"),
  "./components/mockups/walkthrough/AdminFlow.tsx": () => import("../components/mockups/walkthrough/AdminFlow.tsx"),
  "./components/mockups/walkthrough/UserFlow.tsx": () => import("../components/mockups/walkthrough/UserFlow.tsx")
};
