// Re-export all types and DB operations from db.ts
// This file is kept for backward compatibility
export type {
  UserRecord,
  MoodEntry,
  JournalEntry,
  Task,
  RiskAlert,
  DirectMessage,
  SessionNote,
  Goal,
  Appointment,
  AISummaryCache,
} from "./lib/db";

export {
  dbGetUser,
  dbGetUserByEmail,
  dbCreateUser,
  dbGetAllUsers,
  dbGetMoodEntries,
  dbAddMoodEntry,
  dbGetJournalEntries,
  dbAddJournalEntry,
  dbUpdateJournalEntry,
  dbDeleteJournalEntry,
  dbGetTask,
  dbGetUserTasks,
  dbGetAllTasks,
  dbGetTasksByPsychologist,
  dbCreateTask,
  dbCompleteTask,
  dbGetAlert,
  dbGetAlertsByPsychologist,
  dbCreateAlert,
  dbMarkAlertReviewed,
  dbHasRecentAlert,
  dbGetLinkCode,
  dbSetLinkCode,
  dbDeleteLinkCode,
  dbGetClientsByPsychologist,
  dbIsClientOfPsychologist,
  dbAddClientAssignment,
  dbGetPsychologistForClient,
  dbGetThreadKey as getThreadKey,
  dbAddDirectMessage as addDirectMessage,
  dbGetDirectMessages as getDirectMessages,
  dbMarkMessagesRead as markMessagesRead,
  dbGetUnreadCount as getUnreadCount,
  dbGetNotes,
  dbAddNote,
  dbGetGoals,
  dbAddGoal,
  dbUpdateGoal,
  dbGetAppointmentsByPsychologist,
  dbGetAppointmentsByClient,
  dbCreateAppointment,
  dbGetAISummaryCache,
  dbSetAISummaryCache,
  dbGetPushToken,
  dbSetPushToken,
  dbGetPushTokensForClients,
} from "./lib/db";
